version: '3.8'

services:
  # Banco de Dados
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: omnichat_db
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Intamr17@ #MSSQL_SA_PASSWORD=OmniChat@2025! # Mude isso em produção!
    ports:
      - "14333:1433" # Mapeando para 14333 para evitar conflito com SQL Server local
    volumes:
      - mssql_data:/var/opt/mssql

  # Backend (API)
  backend:
    build: ./backend
    container_name: omnichat_api
    depends_on:
      - db
    environment:
      - PORT=3002
      - DB_USER=sa
      - DB_PASS=Intamr17@
      - DB_NAME=OmniChatDev
      - DB_HOST=db
      - JWT_SECRET=Intamr17@
    ports:
      - "3002:3002"
    restart: always

  # Frontend (React + Nginx)
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL= # Deixar vazio para usar caminho relativo do Nginx
    container_name: omnichat_web
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: always

volumes:
  mssql_data:
